[package]
name = "password_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
rusqlite = "0.31.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
